POST http://localhost:5000/news/posting
Content-Type: application/json

{
  "Author": "John Doe",
  "Date": "20250603",
  "Comments": [
    {
    }
  ],
  "Title": "New Discussion Topic",
  "Description": "This is a description of the new discussion topic."
}

###

GET http://localhost:5000/news/posts
Content-Type: application/json

###

GET http://localhost:5000/profile/data
Content-Type: application/json

###

PATCH http://localhost:5000/profile/data/xs43nkIvdKF2sHjDi15u
Content-Type: application/json

{
  "Username": "Testuser",
  "Last_online": "June 5, 2025 at 12:00:00 AM UTC-7"
}